### ISSUE TITLE
Error in format_lyrics when run w/o "--punctuation" argument

### ISSUE THREAD

**Issue by rje6459** [initstring/lyricpass#1]
When the script is run without the --punctuation argument, the following error message is observed:

```
Traceback (most recent call last):
  File "lyricpass.py", line 128, in <module>
    main()
  File "lyricpass.py", line 119, in main
    lyrics = format_lyrics(lyrics)                      # format lyrics as specified in arguments
  File "lyricpass.py", line 90, in format_lyrics
    formatted = [''.join(c for c in s if c not in string.punctuation) for s in formatted]
  File "lyricpass.py", line 90, in <listcomp>
    formatted = [''.join(c for c in s if c not in string.punctuation) for s in formatted]
  File "lyricpass.py", line 90, in <genexpr>
    formatted = [''.join(c for c in s if c not in string.punctuation) for s in formatted]
TypeError: 'in <string>' requires string as left operand, not int
```

**Comment by initstring** [comment]
Can you let me know the exact command you ran?
Thanks!

**Comment by initstring** [comment]
Did not hear back, closing this old issue.
