### ISSUE TITLE
Charmap problem

### ISSUE THREAD

**Issue by AnnualMedia1328** [initstring/lyricpass#10]
[+] Looking up artist Eminem
[+] Found 2200 songs for artists Eminem
Traceback (most recent call last):
  File "C:\Users\andri\Downloads\lyricpass-master\lyricpass-master\lyricpass.py", line 248, in <module>
    main()
  File "C:\Users\andri\Downloads\lyricpass-master\lyricpass-master\lyricpass.py", line 230, in main
    raw_words.update(scrape_lyrics(url_list))
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\Downloads\lyricpass-master\lyricpass-master\lyricpass.py", line 202, in scrape_lyrics
    write_data(LYRIC_FILE, lyrics)
  File "C:\Users\andri\Downloads\lyricpass-master\lyricpass-master\lyricpass.py", line 172, in write_data
    open_file.write(line + '\n')
  File "C:\Users\andri\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1257.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\xe1' in position 1: character maps to <undefined>

**Comment by AnnualMedia1328** [comment]
Fixed it with adding UTF-8 encoding to line 170:
`    with open(outfile, "a", encoding='utf-8') as open_file:`
