### ISSUE TITLE
lyricpass throws error: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by RafaeldelRio** [initstring/lyricpass#8]
Hello,

There's a problem with lyricpass right now. If we use it to make a simple request, like:
`python3 lyricpass.py -a Adele`

It throws the following error:
[+] Looking up artist Adele
Traceback (most recent call last):
  File "/lyricpass-master/lyricpass.py", line 245, in <module>
    main()
  File "/lyricpass-master/lyricpass.py", line 224, in main
    url_list = build_urls(artist)
  File "/lyricpass-master/lyricpass.py", line 141, in build_urls
    with urllib.request.urlopen(query_url) as response:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

I tried to debug the problem but I couldn't find the URL being asked.

**Comment by initstring** [comment]
Hi @RafaeldelRio - thanks for opening an issue!

I think I found the problem. Adding a user agent gets the tool working again.

Please let me know if this doesn't fix it for you, and thanks again for letting me know.
